[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "relax"
version = "0.1.0"
description = "Reinforcement Learning with JAX."
readme = "README.md"
requires-python = ">=3.8"

[tool.black]
line-length = 120
target-version = ['py39']
