alg: diffv2
alpha_lr: 0.007
debug: false
delay_alpha_update: 250
diffusion_hidden_dim: 256
diffusion_steps: 20
env: Ant-v4
hidden_dim: 256
hidden_num: 3
lr: 0.0003
lr_schedule_end: 3.0e-05
noise_scale: 0.1
num_particles: 32
num_vec_envs: 5
seed: 100
start_step: 30000
suffix: large_scale_run
total_step: 1000000
